### ISSUE TITLE
DuckDuckGo as primary search provider

### ISSUE THREAD

**Issue by miller9904** [skylight-software/jonathan#2]
The main strength of Jonathan is that it is a private personal assistant.  [DuckDuckGo](https://duckduckgo.com) is the best private search engine that there is.  This is the only way we can provide completely private searches.  Right now, DuckDuckGo harvests search results from other engines, so they cannot give just anyone access to their API.  We could just open a new browser search every time, but this would get annoying on a mobile device.  DuckDuckGo said that they can partner with 'compelling' projects if they want to (https://duck.co/help/company/partnerships).  Let's see what they will do, but we can't contact them until Jonathan is amazing enough to get them interested.

**Comment by RedRoboHood** [comment]
I think we should do what we can (open a new browser search each time) for now, then once Jonathan is somewhat into the development stage, we can contact DuckDuckGo and see what they have to say.

**Comment by miller9904** [comment]
Sounds good.
